### ISSUE TITLE
how to generate the branch coverage 

### ISSUE THREAD

**Issue by PennaLai** [dbacchet/bazel-coverage-example#1]
I read your document and try it but the report only including the function and line coverage, do you know how to generate the branch coverage?

**Comment by dbacchet** [comment]
Hi @PennaLai , that's more a question for the Bazel project. This repo is just an example I put together to support an open issue (here: https://github.com/bazelbuild/bazel/issues/10825).
You will probably have better luck asking directly there; my guess is that it either depends on the specific bazel+compiler pair or we need to add additional flags to enable more outputs
